<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/3.8.1" created="2014-02-04 22:21" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Example Portfolio</title>
	<link>http://sample.bluehostspoke.com/english</link>
	<description></description>
	<pubDate>Tue, 04 Feb 2014 22:21:56 +0000</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://sample.bluehostspoke.com/english</wp:base_site_url>
	<wp:base_blog_url>http://sample.bluehostspoke.com/english</wp:base_blog_url>

	<wp:author><wp:author_id>7</wp:author_id><wp:author_login>Bluehost SPOKE</wp:author_login><wp:author_email>spoke@bluehost.com</wp:author_email><wp:author_display_name><![CDATA[Bluehost SPOKE]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

	<wp:category><wp:term_id>4</wp:term_id><wp:category_nicename>projects</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Projects]]></wp:cat_name></wp:category>
	<wp:category><wp:term_id>5</wp:term_id><wp:category_nicename>reflections</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Reflections]]></wp:cat_name></wp:category>
	<wp:category><wp:term_id>1</wp:term_id><wp:category_nicename>uncategorized</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Uncategorized]]></wp:cat_name></wp:category>
	<wp:term><wp:term_id>6</wp:term_id><wp:term_taxonomy>nav_menu</wp:term_taxonomy><wp:term_slug>alternative-menu</wp:term_slug><wp:term_name><![CDATA[Alternative Menu]]></wp:term_name></wp:term>

	<generator>http://wordpress.org/?v=3.8.1</generator>

	<item>
				<title>ubt logo</title>
		<link>http://sample.bluehostspoke.com/english/?attachment_id=43</link>
		<pubDate>Thu, 12 Dec 2013 20:52:49 +0000</pubDate>
		<dc:creator><![CDATA[Bluehost SPOKE]]></dc:creator>
		<guid isPermaLink="false"><?php echo get_template_url();?>/attachements/ubt-logo.png</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>43</wp:post_id>
		<wp:post_date>2013-12-12 20:52:49</wp:post_date>
		<wp:post_date_gmt>2013-12-12 20:52:49</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>ubt-logo</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>42</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url><?php echo get_template_url();?>/attachements/ubt-logo.png</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[2013/12/ubt-logo.png]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:5:{s:5:"width";i:160;s:6:"height";i:160;s:4:"file";s:20:"2013/12/ubt-logo.png";s:5:"sizes";a:6:{s:9:"thumbnail";a:4:{s:4:"file";s:20:"ubt-logo-150x150.png";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:9:"image/png";}s:12:"square_small";a:4:{s:4:"file";s:20:"ubt-logo-130x130.png";s:5:"width";i:130;s:6:"height";i:130;s:9:"mime-type";s:9:"image/png";}s:14:"square_smaller";a:4:{s:4:"file";s:18:"ubt-logo-70x70.png";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:9:"image/png";}s:15:"square_smallest";a:4:{s:4:"file";s:18:"ubt-logo-45x45.png";s:5:"width";i:45;s:6:"height";i:45;s:9:"mime-type";s:9:"image/png";}s:12:"grid_fifth_1";a:4:{s:4:"file";s:20:"ubt-logo-160x125.png";s:5:"width";i:160;s:6:"height";i:125;s:9:"mime-type";s:9:"image/png";}s:6:"grid_3";a:4:{s:4:"file";s:20:"ubt-logo-160x150.png";s:5:"width";i:160;s:6:"height";i:150;s:9:"mime-type";s:9:"image/png";}}s:10:"image_meta";a:10:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";}}]]></wp:meta_value>
		</wp:postmeta>
	</item>
</channel>
</rss>
